version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # <-- Si tu app.py está en src, esto mapea backend dentro de /app
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app/src
    command: python /app/src/app.py

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000